# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-frontend-dependencies-{{ checksum "./frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-frontend-dependencies-

      - restore_cache:
          keys:
            - v1-backend-dependencies-{{ checksum "./backend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-backend-dependencies-
      
      - run:  cd ./frontend/ && yarn install

      - save_cache:
          paths:
            - ./frontend/node_modules
          key: v1-frontend-dependencies-{{ checksum "./frontend/package.json" }}
      
      - run:  cd ./backend/ && yarn install
        
      - save_cache:
          paths:
            - ./backend/node_modules
          key: v1-backend-dependencies-{{ checksum "./backend/package.json" }}

      # build and run tests for frontend!
      - run: 
          name: Running tests and building
          command: |
            cd ./frontend/
            echo testing frontend... 
            yarn run test-all
            echo building frontend...
            yarn run build

      # run tests for backend!
      - run:
          name: Running tests
          command: |
            cd ./backend/
            echo testing backend... 
            yarn run test-all
